steps:
  # 1단계 =>  docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0 # 도커 컴포즈 버전
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build

  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  # 3단계 => kubectl set image deployment/my-backend-02-ch-01 my-backend02-sha256-1=asia.gcr.io/myproject01-347906/my-backend02:7.9
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/my-backend-02-ch-01
      - my-backend02-sha256-1=asia.gcr.io/myproject01-347906/my-backend02:7.9
    env: # 환경변수 설정
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-02-1
