version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/myproject01-347906/my-backend02:8 # 새로운 버전 업데이트
    platform: linux/x86_64 # M1은 이거 넣어야함.
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my-database:                   ** GCP에서 SQL을 만들었기 때문에 도커는 이제 사용하지 않는다!! **
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker02'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
