export class CashService {

    checkValue = () => {
        console.log("현금이 있는지 검증한다!!")
         // 1. 고객 가진돈 검증하는 코드 (대략 10줄 정도)
         // ...
         // ...
         // ...
         // ...
    }
}